In [1]:
import os
import pandas as pd

# Load the file
operations = pd.read_csv("lista_operacji.csv", skiprows=25, delimiter=';')

operations["#Data operacji"] = pd.to_datetime(operations["#Data operacji"])

In [44]:
#operations.drop(columns=operations.columns[[2,5,6]], inplace=True)

In [2]:
operations.dtypes

#Data operacji    datetime64[ns]
#Opis operacji            object
#Rachunek                 object
#Kategoria                object
#Kwota                    object
Unnamed: 5               float64
Unnamed: 6               float64
dtype: object

In [3]:
operations.isnull().sum()

#Data operacji      0
#Opis operacji      0
#Rachunek           0
#Kategoria          0
#Kwota              0
Unnamed: 5        230
Unnamed: 6        230
dtype: int64

In [4]:
operations

,#Data operacji,#Opis operacji,#Rachunek,#Kategoria,#Kwota,Unnamed: 5,Unnamed: 6
0,2025-02-24,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,eKonto 2811 ... 1888,Żywność i chemia domowa,"-50,50 PLN",NaN,NaN
1,2025-02-22,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU ...,eKonto 2811 ... 1888,Bez kategorii,"-24,95 PLN",NaN,NaN
2,2025-02-22,Rossmann ZAKUP PRZY UŻYCIU KARTY W KRAJU ...,eKonto 2811 ... 1888,Żywność i chemia domowa,"-23,98 PLN",NaN,NaN
3,2025-02-22,ZABKA Z5482 K.2 ZAKUP PRZY UŻYCIU KARTY W KRA...,eKonto 2811 ... 1888,Żywność i chemia domowa,"-2,50 PLN",NaN,NaN
4,2025-02-22,CINEMA CITY KAZIMIERZ ZAKUP PRZY UŻYCIU KARTY...,eKonto 2811 ... 1888,Wyjścia i wydarzenia,"-35,90 PLN",NaN,NaN
...,...,...,...,...,...,...,...
225,2024-10-04,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,eKonto 2811 ... 1888,Żywność i chemia domowa,"-105,94 PLN",NaN,NaN
226,2024-10-03,FP ONLINE ZAKUP PRZY UŻYCIU KARTY - INTERNET ...,eKonto 2811 ... 1888,Sport i hobby,"-129,00 PLN",NaN,NaN
227,2024-10-02,X-KOM SP. Z O.O. ZAKUP PRZY UŻYCIU KARTY - IN...,eKonto 2811 ... 1888,Elektronika,"-1 765,00 PLN",NaN,NaN
228,2024-10-02,"KARINKA ., TRANSFER . ...",eKonto 2811 ... 1888,Bez kategorii,"-15,00 PLN",NaN,NaN
229,2024-10-01,ZABKA Z5083 K.2 ZAKUP PRZY UŻYCIU KARTY W KRA...,eKonto 2811 ... 1888,Żywność i chemia domowa,"-5,98 PLN",NaN,NaN

In [5]:
operations[['Kwota', 'Waluta']] = operations['#Kwota'].str.extract(r'([-\d,\.]+)\s*(\D+)')

In [6]:
operations.drop(columns=["#Kwota"], inplace=True)

In [7]:
operations

,#Data operacji,#Opis operacji,#Rachunek,#Kategoria,Unnamed: 5,Unnamed: 6,Kwota,Waluta
0,2025-02-24,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,eKonto 2811 ... 1888,Żywność i chemia domowa,NaN,NaN,"-50,50",PLN
1,2025-02-22,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU ...,eKonto 2811 ... 1888,Bez kategorii,NaN,NaN,"-24,95",PLN
2,2025-02-22,Rossmann ZAKUP PRZY UŻYCIU KARTY W KRAJU ...,eKonto 2811 ... 1888,Żywność i chemia domowa,NaN,NaN,"-23,98",PLN
3,2025-02-22,ZABKA Z5482 K.2 ZAKUP PRZY UŻYCIU KARTY W KRA...,eKonto 2811 ... 1888,Żywność i chemia domowa,NaN,NaN,"-2,50",PLN
4,2025-02-22,CINEMA CITY KAZIMIERZ ZAKUP PRZY UŻYCIU KARTY...,eKonto 2811 ... 1888,Wyjścia i wydarzenia,NaN,NaN,"-35,90",PLN
...,...,...,...,...,...,...,...,...
225,2024-10-04,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,eKonto 2811 ... 1888,Żywność i chemia domowa,NaN,NaN,"-105,94",PLN
226,2024-10-03,FP ONLINE ZAKUP PRZY UŻYCIU KARTY - INTERNET ...,eKonto 2811 ... 1888,Sport i hobby,NaN,NaN,"-129,00",PLN
227,2024-10-02,X-KOM SP. Z O.O. ZAKUP PRZY UŻYCIU KARTY - IN...,eKonto 2811 ... 1888,Elektronika,NaN,NaN,-1,
228,2024-10-02,"KARINKA ., TRANSFER . ...",eKonto 2811 ... 1888,Bez kategorii,NaN,NaN,"-15,00",PLN
229,2024-10-01,ZABKA Z5083 K.2 ZAKUP PRZY UŻYCIU KARTY W KRA...,eKonto 2811 ... 1888,Żywność i chemia domowa,NaN,NaN,"-5,98",PLN

In [8]:
operations.drop(columns=operations.columns[[2,4,5]], inplace=True)

In [9]:
operations["#Kategoria"] = operations["#Kategoria"].apply(lambda x: str(x))

In [10]:
operations

operations.loc[
    operations["#Opis operacji"].str.contains(r'\bBLIK P2P\b', regex=True), "#Kategoria"
] = "BLIK"

operations.loc[
    operations["#Opis operacji"].str.contains(r'\b\bPRZELEW|przelew\b\b', regex=True), "#Kategoria"
] = "PRZELEW"

In [11]:
operations["#Opis operacji"] = operations["#Opis operacji"].str.strip()

In [12]:
import re

categories = operations["#Kategoria"].unique().tolist()

operations

,#Data operacji,#Opis operacji,#Kategoria,Kwota,Waluta
0,2025-02-24,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-50,50",PLN
1,2025-02-22,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU,Bez kategorii,"-24,95",PLN
2,2025-02-22,Rossmann ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-23,98",PLN
3,2025-02-22,ZABKA Z5482 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-2,50",PLN
4,2025-02-22,CINEMA CITY KAZIMIERZ ZAKUP PRZY UŻYCIU KARTY...,Wyjścia i wydarzenia,"-35,90",PLN
...,...,...,...,...,...
225,2024-10-04,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-105,94",PLN
226,2024-10-03,FP ONLINE ZAKUP PRZY UŻYCIU KARTY - INTERNET,Sport i hobby,"-129,00",PLN
227,2024-10-02,X-KOM SP. Z O.O. ZAKUP PRZY UŻYCIU KARTY - IN...,Elektronika,-1,
228,2024-10-02,"KARINKA ., TRANSFER . ...",BLIK,"-15,00",PLN
229,2024-10-01,ZABKA Z5083 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-5,98",PLN

In [80]:
category_missin_operations = operations.loc[operations["#Kategoria"] == "Bez kategorii", ]

In [57]:
#categories = operations["#Kategoria"].unique()
from tenacity import retry, wait_random_exponential
from openai import OpenAI
import json
from google import genai

OPENAI_API_KEY = "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"
GOOGLE_API_KEY = "AIzaSyBodmtJ0M3FACNavFKov_rfXDDxnNIJWvo"

client = genai.Client(api_key=GOOGLE_API_KEY)
def category_definition_openai():
    
    client = OpenAI(api_key=OPENAI_API_KEY)
    response = client.responses.create(
    model="gpt-3.5-turbo",
    input="Hello."
    )
    
    return response

@retry(wait=wait_random_exponential(multiplier=1, max=60))
def category_definition_gemini(operation):
    
    question = f'''wybież jedna z podanych kategorii, - {categories} - dla podanego zakupu - 
                zakup: "{operation}" - w swojej odpowiedzi podaj tylko i wyłącznie kategorię i nic więcej'''
     
    response = client.models.generate_content(
        model="gemini-2.0-flash-lite",
        contents=[question]
    )
    
    return response.candidates[0].content.parts[0].text.strip()

In [81]:
for index in operations.index[operations["#Kategoria"] == "Bez kategorii"]:
    response = category_definition_gemini(operations.at[index, "#Opis operacji"])
    operations.at[index, "#Kategoria"] = response

KeyboardInterrupt:

In [13]:
operations

,#Data operacji,#Opis operacji,#Kategoria,Kwota,Waluta
0,2025-02-24,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-50,50",PLN
1,2025-02-22,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU,Bez kategorii,"-24,95",PLN
2,2025-02-22,Rossmann ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-23,98",PLN
3,2025-02-22,ZABKA Z5482 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-2,50",PLN
4,2025-02-22,CINEMA CITY KAZIMIERZ ZAKUP PRZY UŻYCIU KARTY...,Wyjścia i wydarzenia,"-35,90",PLN
...,...,...,...,...,...
225,2024-10-04,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-105,94",PLN
226,2024-10-03,FP ONLINE ZAKUP PRZY UŻYCIU KARTY - INTERNET,Sport i hobby,"-129,00",PLN
227,2024-10-02,X-KOM SP. Z O.O. ZAKUP PRZY UŻYCIU KARTY - IN...,Elektronika,-1,
228,2024-10-02,"KARINKA ., TRANSFER . ...",BLIK,"-15,00",PLN
229,2024-10-01,ZABKA Z5083 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-5,98",PLN

In [83]:
operations["Kwota"] = operations["Kwota"].str.replace(',','.')

In [84]:
operations["Kwota"] = operations["Kwota"].astype('float')

In [85]:
operations

,#Data operacji,#Opis operacji,#Kategoria,Kwota,Waluta
0,2025-02-24,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,-50.50,PLN
1,2025-02-22,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU,Jedzenie poza domem,-24.95,PLN
2,2025-02-22,Rossmann ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,-23.98,PLN
3,2025-02-22,ZABKA Z5482 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,-2.50,PLN
4,2025-02-22,CINEMA CITY KAZIMIERZ ZAKUP PRZY UŻYCIU KARTY...,Wyjścia i wydarzenia,-35.90,PLN
...,...,...,...,...,...
225,2024-10-04,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,-105.94,PLN
226,2024-10-03,FP ONLINE ZAKUP PRZY UŻYCIU KARTY - INTERNET,Sport i hobby,-129.00,PLN
227,2024-10-02,X-KOM SP. Z O.O. ZAKUP PRZY UŻYCIU KARTY - IN...,Elektronika,-1.00,
228,2024-10-02,"KARINKA ., TRANSFER . ...",BLIK,-15.00,PLN
229,2024-10-01,ZABKA Z5083 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,-5.98,PLN

In [15]:
operations.sort_values("#Data operacji", ascending=False)

,#Data operacji,#Opis operacji,#Kategoria,Kwota,Waluta
0,2025-02-24,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-50,50",PLN
4,2025-02-22,CINEMA CITY KAZIMIERZ ZAKUP PRZY UŻYCIU KARTY...,Wyjścia i wydarzenia,"-35,90",PLN
5,2025-02-22,WWW.CINEMA-CITY.PL ...,Wyjścia i wydarzenia,"-67,80",PLN
1,2025-02-22,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU,Bez kategorii,"-24,95",PLN
3,2025-02-22,ZABKA Z5482 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-2,50",PLN
...,...,...,...,...,...
225,2024-10-04,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-105,94",PLN
226,2024-10-03,FP ONLINE ZAKUP PRZY UŻYCIU KARTY - INTERNET,Sport i hobby,"-129,00",PLN
227,2024-10-02,X-KOM SP. Z O.O. ZAKUP PRZY UŻYCIU KARTY - IN...,Elektronika,-1,
228,2024-10-02,"KARINKA ., TRANSFER . ...",BLIK,"-15,00",PLN
229,2024-10-01,ZABKA Z5083 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-5,98",PLN

In [16]:
date_from = operations["#Data operacji"].iloc[-1]
date_to = operations["#Data operacji"].iloc[0]

In [17]:
date_to

Timestamp('2025-02-24 00:00:00')

In [ ]:
date_from

Timestamp('2024-10-01 00:00:00')

In [19]:
from datetime import date
operation_date= date(2024, 5, 1)
operation_date

datetime.date(2024, 5, 1)

In [ ]:
date_from.date()

datetime.date(2024, 10, 1)

In [25]:
operation_date >= date_from.date()

False

In [ ]:
operation_date <= date_to

In [31]:
data_file = operations
data_file

,#Data operacji,#Opis operacji,#Kategoria,Kwota,Waluta
0,2025-02-24,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-50,50",PLN
1,2025-02-22,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU,Bez kategorii,"-24,95",PLN
2,2025-02-22,Rossmann ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-23,98",PLN
3,2025-02-22,ZABKA Z5482 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-2,50",PLN
4,2025-02-22,CINEMA CITY KAZIMIERZ ZAKUP PRZY UŻYCIU KARTY...,Wyjścia i wydarzenia,"-35,90",PLN
...,...,...,...,...,...
225,2024-10-04,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-105,94",PLN
226,2024-10-03,FP ONLINE ZAKUP PRZY UŻYCIU KARTY - INTERNET,Sport i hobby,"-129,00",PLN
227,2024-10-02,X-KOM SP. Z O.O. ZAKUP PRZY UŻYCIU KARTY - IN...,Elektronika,-1,
228,2024-10-02,"KARINKA ., TRANSFER . ...",BLIK,"-15,00",PLN
229,2024-10-01,ZABKA Z5083 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-5,98",PLN

In [32]:
import sys
import os

sys.path.append(os.path.abspath("../backend"))  # <-- kluczowa zmiana

from app.database.models import Operation

user_id = 2

operation = [Operation(
                user_id=user_id,
                operation_date=row["#Data operacji"],
                category=row["#Kategoria"],
                description=row["#Opis operacji"],
                value=row["Kwota"],
                currency=row["Waluta"]) 
                for _, row in data_file.iterrows()]

In [35]:
from typing import List

list_operation : List[Operation] = [[o.operation_id, o.user_id, o.operation_date, o.category, o.description, o.value, o.currency]  for o in operation]
pd.DataFrame(list_operation)

,0,1,2,3,4,5,6
0,None,2,2025-02-24,Żywność i chemia domowa,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,"-50,50",PLN
1,None,2,2025-02-22,Bez kategorii,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU,"-24,95",PLN
2,None,2,2025-02-22,Żywność i chemia domowa,Rossmann ZAKUP PRZY UŻYCIU KARTY W KRAJU,"-23,98",PLN
3,None,2,2025-02-22,Żywność i chemia domowa,ZABKA Z5482 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,"-2,50",PLN
4,None,2,2025-02-22,Wyjścia i wydarzenia,CINEMA CITY KAZIMIERZ ZAKUP PRZY UŻYCIU KARTY...,"-35,90",PLN
...,...,...,...,...,...,...,...
225,None,2,2024-10-04,Żywność i chemia domowa,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,"-105,94",PLN
226,None,2,2024-10-03,Sport i hobby,FP ONLINE ZAKUP PRZY UŻYCIU KARTY - INTERNET,"-129,00",PLN
227,None,2,2024-10-02,Elektronika,X-KOM SP. Z O.O. ZAKUP PRZY UŻYCIU KARTY - IN...,-1,
228,None,2,2024-10-02,BLIK,"KARINKA ., TRANSFER . ...","-15,00",PLN
229,None,2,2024-10-01,Żywność i chemia domowa,ZABKA Z5083 K.2 ZAKUP PRZY UŻYCIU KARTY W KRAJU,"-5,98",PLN

In [68]:
saved_operations = operations.iloc[0:2, :].sort_values(by="Kwota", ascending=True)

new_operations = operations.iloc[0:3, :]

In [69]:
saved_operations

,#Data operacji,#Opis operacji,#Kategoria,Kwota,Waluta
1,2025-02-22,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU,Bez kategorii,"-24,95",PLN
0,2025-02-24,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-50,50",PLN

In [70]:
new_operations

,#Data operacji,#Opis operacji,#Kategoria,Kwota,Waluta
0,2025-02-24,JMP S.A. BIEDRONKA 5987 ZAKUP PRZY UŻYCIU KAR...,Żywność i chemia domowa,"-50,50",PLN
1,2025-02-22,A348 Krakow ZAKUP PRZY UŻYCIU KARTY W KRAJU,Bez kategorii,"-24,95",PLN
2,2025-02-22,Rossmann ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-23,98",PLN

In [71]:
merged_df = new_operations.merge(saved_operations, how='left', indicator=True)

operations_to_add = merged_df[merged_df['_merge'] == 'left_only'].drop(columns=['_merge'])

In [72]:
operations_to_add

,#Data operacji,#Opis operacji,#Kategoria,Kwota,Waluta
2,2025-02-22,Rossmann ZAKUP PRZY UŻYCIU KARTY W KRAJU,Żywność i chemia domowa,"-23,98",PLN

In [ ]:
 # zakładam, że operations to DataFrame wcześniej załadowany

import sys
import os

sys.path.append(os.path.abspath("../backend"))  # <-- kluczowa zmiana

from backend.app.database.models import Operation

operations = [
    Operation(**row.to_dict()) for _, row in data_file.iterrows()
]

TypeError: '#Data operacji' is an invalid keyword argument for Operation

In [ ]:
data_file = operations  # zakładam, że operations to DataFrame wcześniej załadowany

import sys
import os

sys.path.append(os.path.abspath(".."))  # <-- kluczowa zmiana

from backend.app.database.models import Operation

operations = [
    Operation(**row.to_dict()) for _, row in data_file.iterrows()
]

ModuleNotFoundError: No module named 'app'

In [27]:
df1=pd.DataFrame({'A':[1,2],'B':[2,2]})
df2=pd.DataFrame({'A':[1],'B':[2]})

In [19]:
df1

   A  B
0  1  2
1  2  3
2  3  4
3  3  4

In [20]:
df2

   A  B
0  1  2

In [18]:
pd.concat([df1, df2]).drop_duplicates(keep=False)

   A  B
1  2  3

In [28]:
df1[~df1.apply(tuple,1).isin(df2.apply(tuple,1))].shape[0]

1